# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Jason Yundt <jason@jasonyundt.email>
%YAML 1.2
---
repos:
    -
        repo: https://github.com/Jayman2000/jasons-pre-commit-hooks
        rev: v0.3.0
        hooks:
            -
                id: repo-style-checker
            -
                id: detect-bad-unicode
                exclude: &default_excludes '^LICENSES/'
            -
                id: forbid-paths-that-match
                exclude: *default_excludes
                args:
                    - --pattern
                    - ^LICENSE
                    - --pattern
                    - ^COPYING
    -
        repo: https://github.com/fsfe/reuse-tool
        rev: v4.0.3
        hooks:
            -
                id: reuse
    -
        repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
        rev: v0.5.1post1
        hooks:
            -
                id: pre-commit-update
                args: [--dry-run]
                exclude: *default_excludes
    -
        # editorconfig-checker-disable
        # yamllint disable-line rule:line-length
        repo: https://github.com/editorconfig-checker/editorconfig-checker.python
        # editorconfig-checker-enable
        rev: 3.0.3
        hooks:
            -
                id: editorconfig-checker
                exclude: *default_excludes
                args:
                    - -ignore-defaults
                    # Unfortunately, I don’t think that there’s any way
                    # to get Godot to obey the EditorConfig when
                    # generating plain text files.
                    - -exclude
                    - '*.import'
    -
        repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v5.0.0
        hooks:
            -
                id: check-case-conflict
                exclude: *default_excludes
            -
                id: check-merge-conflict
                exclude: *default_excludes
            -
                id: check-symlinks
                exclude: *default_excludes
            -
                id: check-vcs-permalinks
                exclude: *default_excludes
            -
                id: destroyed-symlinks
                exclude: *default_excludes
            -
                id: debug-statements
                exclude: *default_excludes
            -
                id: fix-encoding-pragma
                exclude: *default_excludes
    -
        repo: https://github.com/pre-commit/pygrep-hooks
        rev: v1.10.0
        hooks:
            -
                id: text-unicode-replacement-char
                exclude: *default_excludes
    -
        repo: https://github.com/zricethezav/gitleaks
        rev: v8.20.1
        hooks:
            -
                id: gitleaks
                exclude: *default_excludes
    -
        repo: https://github.com/Jayman2000/yamllint-pr
        rev: pr630-rev-9
        hooks:
            -
                id: yamllint
                exclude: *default_excludes
    -
        repo: https://github.com/igorshubovych/markdownlint-cli
        rev: v0.42.0
        hooks:
            -
                id: markdownlint
                exclude: *default_excludes
    -
        # yamllint disable-line rule:line-length
        repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
        rev: v2.14.0
        hooks:
            -
                id: pretty-format-toml
                exclude: *default_excludes
                args:
                    - --autofix
                    - --indent
                    - '4'
    -
        repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.11.2
        hooks:
            -
                id: mypy
                exclude: *default_excludes
                args:
                    - --strict
                additional_dependencies:
                    - appdirs
                    - appdirs-stubs
                    - reuse
                    - yt-dlp
                    - yt-dlp-types
    -
        repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.6.9
        hooks:
            -
                id: ruff
                exclude: *default_excludes
