# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024–2025 Jason Yundt <jason@jasonyundt.email>

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = ["ttt-build-tool"]
name = "type-that-tune-workspace"
requires-python = ">=3.9"
# This is me trying to say “I don’t want this thing to have version
# numbers.”
version = "0.dev0"

[tool.setuptools]
packages = []

[tool.uv.sources]
ttt-build-tool = {workspace = true}

[tool.uv.workspace]
members = ["python_packages/*"]
