[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "type-that-tune-build-tool"
version = "0"
dependencies = ["yt-dlp"]

[project.scripts]
build-tool = "build_tool:main"

[tool.setuptools.packages.find]
include = ["build_tool"]
